name: 11.0.x

on:
  schedule:
    - cron: '0 0 * * SAT'
  workflow_dispatch:
    branches:
      - main

jobs:
  labwc:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-11.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-11.0.x
      name: "Vanilla Dpup"
      version: 11.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: testing64
      kernel: debian-testing
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-11.0.${{ github.run_number }}-labwc
      retention: 1
  dwl:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-11.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-11.0.x
      name: "Vanilla Dpup"
      version: 11.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: testing64
      kernel: debian-testing
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-11.0.${{ github.run_number }}-dwl
      retention: 1
      variant: dwl
  barebones:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-11.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-11.0.x
      name: "Vanilla Dpup"
      version: 11.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: testing64
      kernel: debian-testing
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-11.0.${{ github.run_number }}-barebones
      retention: 1
      variant: barebones
  retro:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-11.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-11.0.x
      name: "Vanilla Dpup"
      version: 11.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: bookworm64
      kernel: debian-bookworm
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-11.0.${{ github.run_number }}-retro
      retention: 1
      variant: labwc
  upload:
    needs: [labwc, dwl, barebones, retro]
    runs-on: ubuntu-24.04
    steps:
      - name: Download labwc build artifact
        uses: actions/download-artifact@v4
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}-labwc
          path: labwc
      - name: Download dwl build artifact
        uses: actions/download-artifact@v4
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}-dwl
          path: dwl
      - name: Download barebones build artifact
        uses: actions/download-artifact@v4
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}-barebones
          path: barebones
      - name: Download retro build artifact
        uses: actions/download-artifact@v4
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}-retro
          path: retro
      - name: Rename files
        run: |
          for x in labwc dwl barebones retro; do
              mv -f $x/*-bios.img.gz vanilladpup-11.0.${{ github.run_number }}-$x-bios.img.gz || exit 1
              mv -f $x/*-uefi.img.gz vanilladpup-11.0.${{ github.run_number }}-$x-uefi.img.gz || exit 1
              mv -f $x/woof-CE.tar.gz woof-CE-$x.tar.gz || exit 1
          done
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}
          tag_name: vanilladpup-x86_64-11.0.${{ github.run_number }}
          fail_on_unmatched_files: true
          files: |
            *.img.gz
            woof-CE-*.tar.gz
  cleanup:
    needs: [upload]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [x86_64]
    steps:
      - name: Delete old ${{ matrix.arch }} releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1
          delete_tag_pattern: vanilladpup-${{ matrix.arch }}-
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
